[#ftl]
[@b.head/]
[#assign idxNames=["","专业一","专业二","专业三"]/]
[@b.grid items=signupInfoOptions var="signupInfoOption"]
  [@b.gridbar]
    bar.addItem("${b.text("action.export")}",action.exportData("info.code:学号,info.name:姓名,info.gender.name:性别,info.birthday:出生年月,info.idcard:身份证号,info.mobile:电话,info.address:联系地址,info.institution.name:学校,info.department:主修院系,info.major:主修专业,info.squad:班级,info.gpa:绩点,option.major.name:专业,idx:志愿",
    null,'fileName=学生报名信息一览表'));
  [/@]
  [@b.row]
    [@b.boxcol /]
    [@b.col width="8%" property="info.code" title="学号"/]
    [@b.col width="8%" property="info.name" title="姓名"/]
    [@b.col width="12%" property="info.department" title="主修院系"/]
    [@b.col width="12%" property="info.major" title="主修专业"/]
    [@b.col width="6%" property="info.gpa" title="绩点"/]
    [@b.col width="15%" property="option.major.department.name" title="报名院系"/]
    [@b.col property="option.major.name" title="报名专业"/]
    [@b.col width="6%" property="idx" title="报名顺序"]${idxNames[signupInfoOption.idx]!'--'}[/@]
    [@b.col width="7%" property="info.updatedAt" title="报名时间"]${signupInfoOption.info.updatedAt?string("yy-MM-dd")}[/@]
  [/@]
[/@]
[@b.foot/]
